### ISSUE TITLE
.NET 8 MAUI

### ISSUE THREAD

**Issue by FrantisekPregis** [ZebraDevs/datawedge-MAUI-SampleApp#1]
Hi,

I can´t get this running in .NET 8 MAUI, there is some problem with Android framework targeting. My Zebra MC3300 (API 30) device does not show up in Visual Studio 2022 and an Android target is not listed in the project properties. I tried to copy the relevant files to a new project (MainPage, DWIntentReceiver and MainActivity) but the app didn´t do anything when scanning, I probably missed something.

What am I doing wrong?

Frantisek

**Comment by NDZL** [comment]
Hi Frantisek – thanks for your interest in Zebra products.
I recently faced the same issue, as seen below – only the Window Machine target was available, despite Android is configured, installed, and a device is connected
 ***@***.***
***@***.***

I solved going through the following steps

  *   Rebuild the solution
  *   I got the error message
***@***.***

  *   So I ran dotnet workload restore and it installed a ton of stuff – although the target was not new to my installation
[A screenshot of a computer screen  Description automatically generated]

  *   Reboot the development machine

  *   Connect the device, everything runs now smoothly!
[A screen shot of a computer  Description automatically generated]



About the other question you asked, how to get barcode readings,

  *   Be sure to follow what I wrote in the READMe file
  *   On the Zebra device
     *   Preferably reset Datawedge, so you get a clean start: Datawedge / Three dots / Settings / Restore / Yes
     *   For Profile0 enter the following settings in the INTENT OUTPUT Plugin: action, category, delivery as in the picture

If you prefer to change the Action, then it must match that in https://github.com/ZebraDevs/datawedge-MAUI-SampleApp/blob/41dbbed7acc4adaf9157e2666e4f201142ebc624/datawedge-MAUI-SampleApp/Platforms/Android/DWIntentReceiver.cs#L18
***@***.***


  *   Run and Scan!
***@***.***



Nicola De Zolt L.
Software Engineer
ZEBRA TECHNOLOGIES


From: FrantisekPregis ***@***.***>
Sent: Friday, February 2, 2024 10:05 AM
To: ZebraDevs/datawedge-MAUI-SampleApp ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [ZebraDevs/datawedge-MAUI-SampleApp] .NET 8 MAUI (Issue #1)

Hi, I can´t get this running in .NET 8 MAUI, there is some problem with Android framework targeting. My Zebra MC3300 (API 30) device does not show up in Visual Studio 2022 and an Android target is not listed in the project properties. I tried
ZjQcmQRYFpfptBannerStart
External Sender
This message came from outside our organization. Please use caution before acting on the message.
ZjQcmQRYFpfptBannerEnd

Hi,

I can´t get this running in .NET 8 MAUI, there is some problem with Android framework targeting. My Zebra MC3300 (API 30) device does not show up in Visual Studio 2022 and an Android target is not listed in the project properties. I tried to copy the relevant files to a new project (MainPage, DWIntentReceiver and MainActivity) but the app didn´t do anything when scanning, I probably missed something.

What am I doing wrong?

Frantisek

—
Reply to this email directly, view it on GitHub<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_ZebraDevs_datawedge-2DMAUI-2DSampleApp_issues_1&d=DwMFaQ&c=Qwsh1H-X9ypOoLLEcAIltRyC0Dw0FG3Mmyd56ahml5w&r=U1B3Lk8Honsy_xtgC17ZQ7saNKD_TQhFfmjOeDxJ__A&m=lc4mnzvJiewyArpyqxw9lZ0SIvCR65112-ziLSEp10bO603qFu4lr3eFdIh9Z2R2&s=7ERCq2ooBD8w5-YY0J24jvTQ8V8sUweso0u1IgjCOvQ&e=>, or unsubscribe<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_ACW36NBRQTO2SJGDKZU6Q2DYRST4XAVCNFSM6AAAAABCWKIPMCVHI2DSMVQWIX3LMV43ASLTON2WKOZSGEYTINBUGM3DQNI&d=DwMFaQ&c=Qwsh1H-X9ypOoLLEcAIltRyC0Dw0FG3Mmyd56ahml5w&r=U1B3Lk8Honsy_xtgC17ZQ7saNKD_TQhFfmjOeDxJ__A&m=lc4mnzvJiewyArpyqxw9lZ0SIvCR65112-ziLSEp10bO603qFu4lr3eFdIh9Z2R2&s=wu7Gn_tjxY24N83bbVhnsCvlRXV1NPjI-u3TLRSAyTU&e=>.
You are receiving this because you are subscribed to this thread.Message ID: ***@***.******@***.***>>


________________________________
- CONFIDENTIAL-
This email and any files transmitted with it are confidential, and may also be legally privileged. If you are not the intended recipient, you may not review, use, copy, or distribute this message. If you receive this email in error, please notify the sender immediately by reply email and then delete this email.

**Comment by NDZL** [comment]
Frantisek, my reply via email dropped the pictures, see the PDF attached. 
br
NDZL

[MAUI DW Issue.pdf](https://github.com/ZebraDevs/datawedge-MAUI-SampleApp/files/14139109/MAUI.DW.Issue.pdf)

**Comment by FrantisekPregis** [comment]
Thanks for the quick response, I got it working! Just another quick question: do you have a similar simple example of sending intents to the device? If I e.g. want to turn off the scanner. I experimentally added three lines of code in your receiving class, just to quickly test turning the scanner off but it didn´t work. This should be a part of some "BroadcastSender" class - but how should it be done? Sorry for mixing another question with this issue, but many people would like to know I guess... Or is there any .NET documention which could be used? I searched, but found only Java / Android examples.

	public class DWIntentReceiver : BroadcastReceiver
	{
		public override void OnReceive(Context context, Intent intent)
		{
			//System.Console.WriteLine("Here is DW on MAUI");
			if (intent.Extras != null)
			{
				String bc_type = intent.Extras.GetString("com.symbol.datawedge.label_type");
				String bc_data = intent.Extras.GetString("com.symbol.datawedge.data_string");

				WeakReferenceMessenger.Default.Send(bc_type + " "+ bc_data);

                **intent.SetAction("com.symbol.datawedge.api.ACTION");
                intent.PutExtra("com.symbol.datawedge.api.SCANNER_INPUT_PLUGIN", "DISABLE_PLUGIN");
                context.SendBroadcast(intent);**
            }
		}
	}

**Comment by NDZL** [comment]
A new commit is now available with a DW off/on feature added.
FYI DW Intent APIs reference is found here https://techdocs.zebra.com/datawedge/latest/guide/api/

**Comment by FrantisekPregis** [comment]
Thanks, I will try it out!

**Comment by MinaSafwatWDX** [comment]
Hello,

I was checking the Maui Code using Datawedge on the GitHub, below

https://github.com/ZebraDevs/datawedge-MAUI-SampleApp/blob/master/datawedge-MAUI-SampleApp/Resources/Raw/dwprofile_com.ndzl.dwmaui.db

and I have no idea how this file is generated "dwprofile_com.ndzl.dwmaui.db"?

also is there any sample code for using Datawedge in Maui Blazor app

**Comment by NDZL** [comment]
Hi MinaSafwatWDX pls see my suggestions at https://developer.zebra.com/content/maui-blazor-datawedge
