### ISSUE TITLE
Datawedge Get active profile

### ISSUE THREAD

**Issue by fgonc124** [ZebraDevs/datawedge-MAUI-SampleApp#3]
I'v been trying to get Datawedge  active profile using .Net Maui but I could not get it one.

This the code that I use to get the job done is:

Intent i = new Intent();
i.SetAction("com.symbol.datawedge.api.ACTION");
i.AddCategory("android.intent.category.DEFAULT");
i.PutExtra("com.symbol.datawedge.api.GET_ACTIVE_PROFILE","");

this.SendBroadcast(i);

The broadcastreceiver isn't activated.

I tried several times and with two different devices, TC21 and TC27.

TC21 has Android 11 and Datawedge 11.4.42
TC27 has Android 13 and Datawedge 13.0.107

Thanks

Fernando
fernandomg4@gmail.com

**Comment by NDZL** [comment]
Hi Fernando - going to check and get back to you

br
Nicola dzl


Nicola De Zolt L.

Software Engineer

ZEBRA TECHNOLOGIES



________________________________
From: fgonc124 ***@***.***>
Sent: Friday, November 1, 2024 8:26:07 PM
To: ZebraDevs/datawedge-MAUI-SampleApp ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [ZebraDevs/datawedge-MAUI-SampleApp] Datawedge Get active profile (Issue #3)

I'v been trying to get Datawedge active profile using .Net Maui but I could not get it one. This the code that I use to get the job done is: Intent i = new Intent(); i. SetAction("com. symbol. datawedge. api. ACTION"); i. AddCategory("android. intent. category. DEFAULT");
ZjQcmQRYFpfptBannerStart
External Sender
This message came from outside our organization. Please use caution before acting on the message.

ZjQcmQRYFpfptBannerEnd

I'v been trying to get Datawedge active profile using .Net Maui but I could not get it one.

This the code that I use to get the job done is:

Intent i = new Intent();
i.SetAction("com.symbol.datawedge.api.ACTION");
i.AddCategory("android.intent.category.DEFAULT");
i.PutExtra("com.symbol.datawedge.api.GET_ACTIVE_PROFILE","");

this.SendBroadcast(i);

The broadcastreceiver isn't activated.

I tried several times and with two different devices, TC21 and TC27.

TC21 has Android 11 and Datawedge 11.4.42
TC27 has Android 13 and Datawedge 13.0.107

Thanks

Fernando
***@***.******@***.***>

—
Reply to this email directly, view it on GitHub<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_ZebraDevs_datawedge-2DMAUI-2DSampleApp_issues_3&d=DwMCaQ&c=Qwsh1H-X9ypOoLLEcAIltRyC0Dw0FG3Mmyd56ahml5w&r=U1B3Lk8Honsy_xtgC17ZQ7saNKD_TQhFfmjOeDxJ__A&m=xMz_0trEC8wQZt3KUf4KXR2OHu8MGvNIKHk_lXJjFKIzBy-AuqoDiRWooLgtDh17&s=Yk0lH4VD6-SpkVzTPH9W3Dm-IOGMI_trly7-A-18dEg&e=>, or unsubscribe<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_ACW36NA4JTTLWK2SOCOI2MLZ6PIU7AVCNFSM6AAAAABRA2RUZWVHI2DSMVQWIX3LMV43ASLTON2WKOZSGYZDSNZSGY2TMNQ&d=DwMCaQ&c=Qwsh1H-X9ypOoLLEcAIltRyC0Dw0FG3Mmyd56ahml5w&r=U1B3Lk8Honsy_xtgC17ZQ7saNKD_TQhFfmjOeDxJ__A&m=xMz_0trEC8wQZt3KUf4KXR2OHu8MGvNIKHk_lXJjFKIzBy-AuqoDiRWooLgtDh17&s=6QP1_tC8hKmfcUM16rU_xufDARrVljqNH-lSKw3l1Ao&e=>.
You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>


________________________________
- CONFIDENTIAL-
This email and any files transmitted with it are confidential, and may also be legally privileged. If you are not the intended recipient, you may not review, use, copy, or distribute this message. If you receive this email in error, please notify the sender immediately by reply email and then delete this email.

**Comment by NDZL** [comment]
Fernando, please see the latest published version (v1.2)

Key points to get the active profile are:

  *
Registering the right action: https://github.com/ZebraDevs/datawedge-MAUI-SampleApp/blob/30b5e0d002e4b4a795b95dd29b7d3fe1ac7091f0/datawedge-MAUI-SampleApp/Platforms/Android/MainActivity.cs#L85

  *
Getting the right extra: https://github.com/ZebraDevs/datawedge-MAUI-SampleApp/blob/30b5e0d002e4b4a795b95dd29b7d3fe1ac7091f0/datawedge-MAUI-SampleApp/Platforms/Android/DWIntentReceiver.cs#L35


Please confirm receipt of this thanks





Nicola De Zolt L.

Software Engineer

ZEBRA TECHNOLOGIES






________________________________
From: fgonc124 ***@***.***>
Sent: Friday, November 1, 2024 8:26 PM
To: ZebraDevs/datawedge-MAUI-SampleApp ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [ZebraDevs/datawedge-MAUI-SampleApp] Datawedge Get active profile (Issue #3)

External Sender
This message came from outside our organization. Please use caution before acting on the message.


I'v been trying to get Datawedge active profile using .Net Maui but I could not get it one.

This the code that I use to get the job done is:

Intent i = new Intent();
i.SetAction("com.symbol.datawedge.api.ACTION");
i.AddCategory("android.intent.category.DEFAULT");
i.PutExtra("com.symbol.datawedge.api.GET_ACTIVE_PROFILE","");

this.SendBroadcast(i);

The broadcastreceiver isn't activated.

I tried several times and with two different devices, TC21 and TC27.

TC21 has Android 11 and Datawedge 11.4.42
TC27 has Android 13 and Datawedge 13.0.107

Thanks

Fernando
***@***.******@***.***>

—
Reply to this email directly, view it on GitHub<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_ZebraDevs_datawedge-2DMAUI-2DSampleApp_issues_3&d=DwMCaQ&c=Qwsh1H-X9ypOoLLEcAIltRyC0Dw0FG3Mmyd56ahml5w&r=U1B3Lk8Honsy_xtgC17ZQ7saNKD_TQhFfmjOeDxJ__A&m=xMz_0trEC8wQZt3KUf4KXR2OHu8MGvNIKHk_lXJjFKIzBy-AuqoDiRWooLgtDh17&s=Yk0lH4VD6-SpkVzTPH9W3Dm-IOGMI_trly7-A-18dEg&e=>, or unsubscribe<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_ACW36NA4JTTLWK2SOCOI2MLZ6PIU7AVCNFSM6AAAAABRA2RUZWVHI2DSMVQWIX3LMV43ASLTON2WKOZSGYZDSNZSGY2TMNQ&d=DwMCaQ&c=Qwsh1H-X9ypOoLLEcAIltRyC0Dw0FG3Mmyd56ahml5w&r=U1B3Lk8Honsy_xtgC17ZQ7saNKD_TQhFfmjOeDxJ__A&m=xMz_0trEC8wQZt3KUf4KXR2OHu8MGvNIKHk_lXJjFKIzBy-AuqoDiRWooLgtDh17&s=6QP1_tC8hKmfcUM16rU_xufDARrVljqNH-lSKw3l1Ao&e=>.
You are receiving this because you are subscribed to this thread.


________________________________
- CONFIDENTIAL-
This email and any files transmitted with it are confidential, and may also be legally privileged. If you are not the intended recipient, you may not review, use, copy, or distribute this message. If you receive this email in error, please notify the sender immediately by reply email and then delete this email.

**Comment by fgonc124** [comment]
Hi Nicola

Thank you for your help.
It worked. 
I was choosing the right extra.
The problem was the action that was the wrong one. That's why the receiver was not activated.

Do you ever worked with Simulscan?
I only receive in receiver one codbar instead of five.

Thanks

**Comment by NDZL** [comment]
Hi Fernando - about Simulscan, ensure you understand the basics from this document https://techdocs.zebra.com/datawedge/latest/guide/input/barcode/#nextgensimulscanconfiguration

Decide whether to stick to a Multibarcode detection (easier, no template) or the Document Capture action (more complex, requires template definition)

Any choice, my advice is to practice with the DWDemo sample app that comes prebuilt in our Android.

Once done with that, work on a profile specifically associated with your application, enable the Intent Output and consume it from your app following https://techdocs.zebra.com/datawedge/13-0/guide/output/intent/#udimultipledecodemode for the multibarcode option.
For the Doc Capture option, the output requires content providers to be used. See here https://techdocs.zebra.com/datawedge/13-0/guide/input/barcode/#documentselectiondocumentcapture and https://techdocs.zebra.com/datawedge/13-0/guide/programmers-guides/content-provider/#processscandatawithnextgensimulscan

Hope this helps.

br


Nicola De Zolt L.

Software Engineer

ZEBRA TECHNOLOGIES



________________________________
