### ISSUE TITLE
DAtawedge NG Simulscan

### ISSUE THREAD

**Issue by fgonc124** [ZebraDevs/datawedge-MAUI-SampleApp#4]
I've been trying Zebra NG Simulscan.

I manage to get response from Datawedge.

Using C# I'm unable to extract data from the response I receive.

Using java I get a bundle with several bundles according to the number of barcode I scanned.
But using  C# after this instruction
              var myObject1 = intent.GetSerializableExtra("com.symbol.datawedge.barcodes");

var myObject1  gets an structure wich I' unable to extract usefull information

![image](https://github.com/user-attachments/assets/94cb4264-7a61-46dd-a5d0-b8c6ffa05adb)

Do you have any idea how to treat this in order to get useful information?

Thanks

Fernando

**Comment by fgonc124** [comment]
This is what I get using Java with Android Studio

![image](https://github.com/user-attachments/assets/962af2dd-f85d-4519-afc9-005e40faef77)

**Comment by NDZL** [comment]
re-posting since email replies do not support md

Hi Fernando, see here
https://github.com/ZebraDevs/datawedge-MAUI-SampleApp/blob/b9fa5bd2556be52ad8230f11dc79882aac21a9cd/datawedge-MAUI-SampleApp/Platforms/Android/DWIntentReceiver.cs#L31

The key is to use GetParcelableArrayList or similar API.

In my case, Profile0 was configured as

![image](https://github.com/user-attachments/assets/696e0417-1238-493e-959a-4473e4699f5e)


And

![image](https://github.com/user-attachments/assets/adc03c63-5a84-4bf7-9418-303affd24309)


So barcodes are reported only once when all 5 are read.

Result

![image](https://github.com/user-attachments/assets/386936d9-c5bb-42f7-8478-6601b8d8afd2)


reference image

![image](https://github.com/user-attachments/assets/d7e34ab6-a0fc-4abb-aad9-8ebc96cc3aa4)


br

**Comment by NDZL** [comment]
.

**Comment by fgonc124** [comment]
Hi Nicola.
It worked.

Thank you for your help, again.
